# Since essentia is still existing in legacy Python,
# we are stuck there too
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r unittests/requirements

# command to run tests
script: 
  - nosetests unittests/modefunctiontest.py

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install numpy
  - pip install python-dateutil
  - pip install scipy

notifications: 
  email: false